[versions]
agp = "8.13.1"
kotlin = "2.0.21"
coreKtx = "1.17.0"
junit = "4.13.2"
junitVersion = "1.3.0"
espressoCore = "3.7.0"
lifecycleRuntimeKtx = "2.9.4"
activityCompose = "1.12.0"
composeBom = "2024.09.00"
appcompat = "1.7.1"
constraintlayout = "2.2.1"
material = "1.12.0"
zxing = "4.3.0"
rxandroid = "3.0.2"
rxjava = "3.1.5"
okhttp = "3.14.9"
okhttptls = "3.14.9"
jsch = "0.1.55"
slf4j = "1.7.36"
gson = "2.10.1"
jaxb = "2.3.1"
commonsnet = "3.9.0"
cardview = "1.0.0"
avloading = "2.3.0"

[libraries]
androidx-core-ktx = { group = "androidx.core", name = "core-ktx", version.ref = "coreKtx" }
junit = { group = "junit", name = "junit", version.ref = "junit" }
androidx-junit = { group = "androidx.test.ext", name = "junit", version.ref = "junitVersion" }
androidx-espresso-core = { group = "androidx.test.espresso", name = "espresso-core", version.ref = "espressoCore" }
androidx-lifecycle-runtime-ktx = { group = "androidx.lifecycle", name = "lifecycle-runtime-ktx", version.ref = "lifecycleRuntimeKtx" }
androidx-activity-compose = { group = "androidx.activity", name = "activity-compose", version.ref = "activityCompose" }
androidx-compose-bom = { group = "androidx.compose", name = "compose-bom", version.ref = "composeBom" }
androidx-compose-ui = { group = "androidx.compose.ui", name = "ui" }
androidx-compose-ui-graphics = { group = "androidx.compose.ui", name = "ui-graphics" }
androidx-compose-ui-tooling = { group = "androidx.compose.ui", name = "ui-tooling" }
androidx-compose-ui-tooling-preview = { group = "androidx.compose.ui", name = "ui-tooling-preview" }
androidx-compose-ui-test-manifest = { group = "androidx.compose.ui", name = "ui-test-manifest" }
androidx-compose-ui-test-junit4 = { group = "androidx.compose.ui", name = "ui-test-junit4" }
androidx-compose-material3 = { group = "androidx.compose.material3", name = "material3" }
androidx-appcompat = { group = "androidx.appcompat", name = "appcompat", version.ref = "appcompat" }
constraintlayout = { group = "androidx.constraintlayout", name = "constraintlayout", version.ref = "constraintlayout" }
material = { group = "com.google.android.material", name = "material", version.ref = "material" }
rxandroid = { module = "io.reactivex.rxjava3:rxandroid", version.ref = "rxandroid" }
rxjava = { module = "io.reactivex.rxjava3:rxjava", version.ref = "rxjava"}
okhttp = { module = "com.squareup.okhttp3:okhttp", version.ref = "okhttp"}
okhttptls = { module = "com.squareup.okhttp3:okhttp-tls", version.ref = "okhttptls"}
zxing = { module = "com.journeyapps:zxing-android-embedded", version.ref = "zxing"}
jsch = { module = "com.jcraft:jsch", version.ref = "jsch"}
slf4j = { module = "org.slf4j:slf4j-api", version.ref = "slf4j"}
gson = { module = "com.google.code.gson:gson", version.ref = "gson"}
jaxb = { group = "javax.xml.bind", name = "jaxb-api", version.ref = "jaxb" }
commonsnet = {module="commons-net:commons-net", version.ref="commonsnet"}
cardview = {module="androidx.cardview:cardview", version.ref="cardview"}
avloading = { module = "io.github.maitrungduc1410:AVLoadingIndicatorView", version.ref = "avloading" }

[plugins]
android-application = { id = "com.android.application", version.ref = "agp" }
kotlin-android = { id = "org.jetbrains.kotlin.android", version.ref = "kotlin" }
kotlin-compose = { id = "org.jetbrains.kotlin.plugin.compose", version.ref = "kotlin" }

